### ISSUE TITLE
How to compile portmodule's example_build modulemanager and module

### ISSUE THREAD

**Issue by MinghaoLin2000** [eclipse-threadx/threadx#234]
I want to know how to compile ports_module/cortex_m3/gnu/example_build/  module and moduleManager together. I checked four bat files. I found that these bat files only output individual binary files.  However, I want to output a binary that contains the module and module manager example code.

**Comment by andrejm-rtos** [comment]
The examples are made to generate two output files for flexibility. Your debugger should be able to load more than one file, check your documentation. If you want to generate one binary file out of two (or more) you can use some of the tools from your toolchain. If you are using the GNU Compiler Collection, you can look into binutils, specifically objcopy.
