### ISSUE TITLE
Will ThreadX support osDelayUntil function in the future？

### ISSUE THREAD

**Issue by IACU** [eclipse-threadx/threadx#393]
osDelayUntil is the CMSIS RTOSv2 API, other OS such as FreeRTOS support this function.tx_thread_sleep support Relative-delay not Absolute-delay in thread function.It means there is a deviation in the running cycle of periodic-threads.

**Comment by Hnz2** [comment]
Hi IACU,

But if this is important for you, you can calculate relative delay from _tx_time_get()_. I don't see any reason to have implemented API like _osDelayUntil()_.

Jan

**Comment by Hnz2** [comment]
Hi @IACU,
I don't believe that RTOS sleep at any type of RTOS was designed for such precision timing. Even with FreeRTOS you will see jitter near to RTOS tick when _osDelayUntil()_ API is used. For more precisions timing should be used another approaches (e.g. hardware timers with semaphore, events or message queue).
Jan

**Comment by IACU** [comment]
> Hi @IACU, I don't believe that RTOS sleep at any type of RTOS was designed for such precision timing. Even with FreeRTOS you will see jitter near to RTOS tick when _osDelayUntil()_ API is used. For more precisions timing should be used another approaches (e.g. hardware timers with semaphore, events or message queue). Jan

OK, thanks for your reply

**Comment by rahmanih** [comment]
closing this item as answered.
