### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by xray-bit** [eclipse-threadx/threadx#410]

**Comment by Hnz2** [comment]
I afraid that it is.

**Comment by amgross** [comment]
From what I understand no, it is just in freeze for while due to long transition of it from microsoft to eclipse.
You can connect to the eclipse threadx mailing list

**Comment by fdesbiens** [comment]
@amgross is right, @Hnz2.

We have been focused on putting things into place what we need to provide access to the safety manuals and support the certification of ThreadX 6.4.1. 

We fixed some CVEs a few months ago. 

Some of the committers have been working on changes which are not done yet.

The mailing list is here: https://accounts.eclipse.org/mailing-list/threadx

You need an Eclipse Foundation account to subscribe.

More to come. We have an announcement coming.

**Comment by xray-bit** [comment]
okay. thanks for letting us know.
